# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Awale_QT/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TIPE(object):
    def setupUi(self, TIPE):
        TIPE.setObjectName("TIPE")
        TIPE.resize(1186, 805)
        self.centralWidget = QtWidgets.QWidget(TIPE)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.pushButtonPlay = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonPlay.setObjectName("pushButtonPlay")
        self.gridLayout.addWidget(self.pushButtonPlay, 5, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 6, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 4, 0, 1, 1)
        self.horizontalLayoutView = QtWidgets.QHBoxLayout()
        self.horizontalLayoutView.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayoutView.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayoutView.setSpacing(6)
        self.horizontalLayoutView.setObjectName("horizontalLayoutView")
        self.pushButtonViewPlayer1 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonViewPlayer1.setCheckable(True)
        self.pushButtonViewPlayer1.setObjectName("pushButtonViewPlayer1")
        self.horizontalLayoutView.addWidget(self.pushButtonViewPlayer1)
        self.pushButtonViewPlayer2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonViewPlayer2.setCheckable(True)
        self.pushButtonViewPlayer2.setObjectName("pushButtonViewPlayer2")
        self.horizontalLayoutView.addWidget(self.pushButtonViewPlayer2)
        self.gridLayout.addLayout(self.horizontalLayoutView, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 0, 1, 1)
        self.formLayoutNewGame = QtWidgets.QFormLayout()
        self.formLayoutNewGame.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayoutNewGame.setContentsMargins(11, 11, 11, 11)
        self.formLayoutNewGame.setSpacing(6)
        self.formLayoutNewGame.setObjectName("formLayoutNewGame")
        self.labelPlayer1 = QtWidgets.QLabel(self.centralWidget)
        self.labelPlayer1.setObjectName("labelPlayer1")
        self.formLayoutNewGame.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelPlayer1)
        self.comboBoxPlayer1 = QtWidgets.QComboBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxPlayer1.sizePolicy().hasHeightForWidth())
        self.comboBoxPlayer1.setSizePolicy(sizePolicy)
        self.comboBoxPlayer1.setObjectName("comboBoxPlayer1")
        self.formLayoutNewGame.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBoxPlayer1)
        self.labelPlayer2 = QtWidgets.QLabel(self.centralWidget)
        self.labelPlayer2.setObjectName("labelPlayer2")
        self.formLayoutNewGame.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelPlayer2)
        self.comboBoxPlayer2 = QtWidgets.QComboBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxPlayer2.sizePolicy().hasHeightForWidth())
        self.comboBoxPlayer2.setSizePolicy(sizePolicy)
        self.comboBoxPlayer2.setObjectName("comboBoxPlayer2")
        self.formLayoutNewGame.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBoxPlayer2)
        self.pushButtonNewGame = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonNewGame.sizePolicy().hasHeightForWidth())
        self.pushButtonNewGame.setSizePolicy(sizePolicy)
        self.pushButtonNewGame.setObjectName("pushButtonNewGame")
        self.formLayoutNewGame.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.pushButtonNewGame)
        self.spinBoxDepth1 = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBoxDepth1.setObjectName("spinBoxDepth1")
        self.formLayoutNewGame.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBoxDepth1)
        self.spinBoxDepth2 = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBoxDepth2.setObjectName("spinBoxDepth2")
        self.formLayoutNewGame.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBoxDepth2)
        self.gridLayout.addLayout(self.formLayoutNewGame, 3, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.graphicsViewDefault = QtWidgets.QGraphicsView(self.centralWidget)
        self.graphicsViewDefault.setEnabled(True)
        self.graphicsViewDefault.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.graphicsViewDefault.setObjectName("graphicsViewDefault")
        self.horizontalLayout.addWidget(self.graphicsViewDefault)
        self.graphicsViewPlayer1 = QtWidgets.QGraphicsView(self.centralWidget)
        self.graphicsViewPlayer1.setEnabled(True)
        self.graphicsViewPlayer1.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.graphicsViewPlayer1.setObjectName("graphicsViewPlayer1")
        self.horizontalLayout.addWidget(self.graphicsViewPlayer1)
        self.graphicsViewPlayer2 = QtWidgets.QGraphicsView(self.centralWidget)
        self.graphicsViewPlayer2.setEnabled(True)
        self.graphicsViewPlayer2.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.graphicsViewPlayer2.setObjectName("graphicsViewPlayer2")
        self.horizontalLayout.addWidget(self.graphicsViewPlayer2)
        TIPE.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(TIPE)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1186, 25))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        TIPE.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(TIPE)
        self.statusBar.setObjectName("statusBar")
        TIPE.setStatusBar(self.statusBar)
        self.actionOpen = QtWidgets.QAction(TIPE)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(TIPE)
        QtCore.QMetaObject.connectSlotsByName(TIPE)

    def retranslateUi(self, TIPE):
        _translate = QtCore.QCoreApplication.translate
        TIPE.setWindowTitle(_translate("TIPE", "MainWindow"))
        self.pushButtonPlay.setText(_translate("TIPE", "Play"))
        self.pushButtonPlay.setShortcut(_translate("TIPE", "Return"))
        self.pushButtonViewPlayer1.setText(_translate("TIPE", "Player 1"))
        self.pushButtonViewPlayer1.setShortcut(_translate("TIPE", "Shift+1"))
        self.pushButtonViewPlayer2.setText(_translate("TIPE", "Player 2"))
        self.pushButtonViewPlayer2.setShortcut(_translate("TIPE", "Shift+2"))
        self.labelPlayer1.setText(_translate("TIPE", "Player 1"))
        self.labelPlayer2.setText(_translate("TIPE", "Player 2"))
        self.pushButtonNewGame.setText(_translate("TIPE", "New Game"))
        self.menuFile.setTitle(_translate("TIPE", "Fi&le"))
        self.actionOpen.setText(_translate("TIPE", "&Open"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TIPE = QtWidgets.QMainWindow()
    ui = Ui_TIPE()
    ui.setupUi(TIPE)
    TIPE.show()
    sys.exit(app.exec_())

